const HSK_DATA=[
{h:"我",p:"wǒ",m:"Tôi",l:1},{h:"你",p:"nǐ",m:"Bạn",l:1},{h:"他",p:"tā",m:"Anh ấy",l:1},
{h:"她",p:"tā",m:"Cô ấy",l:1},{h:"们",p:"men",m:"Các (hậu tố số nhiều)",l:1},
{h:"这",p:"zhè",m:"Này, đây",l:1},{h:"那",p:"nà",m:"Kia, đó",l:1},
{h:"哪",p:"nǎ",m:"Nào, ở đâu",l:1},{h:"谁",p:"shéi",m:"Ai",l:1},
{h:"什么",p:"shénme",m:"Cái gì",l:1},{h:"多少",p:"duōshao",m:"Bao nhiêu",l:1},
{h:"几",p:"jǐ",m:"Mấy",l:1},{h:"怎么",p:"zěnme",m:"Thế nào",l:1},
{h:"怎么样",p:"zěnmeyàng",m:"Như thế nào",l:1},
{h:"是",p:"shì",m:"Là",l:1},{h:"有",p:"yǒu",m:"Có",l:1},
{h:"不",p:"bù",m:"Không",l:1},{h:"没",p:"méi",m:"Chưa, không có",l:1},
{h:"好",p:"hǎo",m:"Tốt, được",l:1},{h:"大",p:"dà",m:"To, lớn",l:1},
{h:"小",p:"xiǎo",m:"Nhỏ, bé",l:1},{h:"多",p:"duō",m:"Nhiều",l:1},
{h:"少",p:"shǎo",m:"Ít",l:1},{h:"冷",p:"lěng",m:"Lạnh",l:1},
{h:"热",p:"rè",m:"Nóng",l:1},{h:"高兴",p:"gāoxìng",m:"Vui vẻ",l:1},
{h:"漂亮",p:"piàoliang",m:"Đẹp",l:1},
{h:"一",p:"yī",m:"Một",l:1},{h:"二",p:"èr",m:"Hai",l:1},{h:"三",p:"sān",m:"Ba",l:1},
{h:"四",p:"sì",m:"Bốn",l:1},{h:"五",p:"wǔ",m:"Năm",l:1},{h:"六",p:"liù",m:"Sáu",l:1},
{h:"七",p:"qī",m:"Bảy",l:1},{h:"八",p:"bā",m:"Tám",l:1},{h:"九",p:"jiǔ",m:"Chín",l:1},
{h:"十",p:"shí",m:"Mười",l:1},{h:"百",p:"bǎi",m:"Trăm",l:1},
{h:"个",p:"gè",m:"Cái (lượng từ)",l:1},{h:"岁",p:"suì",m:"Tuổi",l:1},
{h:"块",p:"kuài",m:"Đồng (tiền), miếng",l:1},
{h:"人",p:"rén",m:"Người",l:1},{h:"家",p:"jiā",m:"Nhà, gia đình",l:1},
{h:"学校",p:"xuéxiào",m:"Trường học",l:1},{h:"医院",p:"yīyuàn",m:"Bệnh viện",l:1},
{h:"商店",p:"shāngdiàn",m:"Cửa hàng",l:1},{h:"饭店",p:"fàndiàn",m:"Nhà hàng, khách sạn",l:1},
{h:"中国",p:"Zhōngguó",m:"Trung Quốc",l:1},{h:"北京",p:"Běijīng",m:"Bắc Kinh",l:1},
{h:"上",p:"shàng",m:"Trên",l:1},{h:"下",p:"xià",m:"Dưới",l:1},
{h:"前面",p:"qiánmiàn",m:"Phía trước",l:1},{h:"后面",p:"hòumiàn",m:"Phía sau",l:1},
{h:"里",p:"lǐ",m:"Trong",l:1},
{h:"今天",p:"jīntiān",m:"Hôm nay",l:1},{h:"明天",p:"míngtiān",m:"Ngày mai",l:1},
{h:"昨天",p:"zuótiān",m:"Hôm qua",l:1},{h:"上午",p:"shàngwǔ",m:"Buổi sáng",l:1},
{h:"下午",p:"xiàwǔ",m:"Buổi chiều",l:1},{h:"中午",p:"zhōngwǔ",m:"Buổi trưa",l:1},
{h:"年",p:"nián",m:"Năm",l:1},{h:"月",p:"yuè",m:"Tháng",l:1},
{h:"日",p:"rì",m:"Ngày",l:1},{h:"星期",p:"xīngqī",m:"Tuần",l:1},
{h:"点",p:"diǎn",m:"Giờ (thời gian)",l:1},{h:"分钟",p:"fēnzhōng",m:"Phút",l:1},
{h:"现在",p:"xiànzài",m:"Bây giờ",l:1},{h:"时候",p:"shíhou",m:"Lúc, khi",l:1},
{h:"爸爸",p:"bàba",m:"Bố",l:1},{h:"妈妈",p:"māma",m:"Mẹ",l:1},
{h:"儿子",p:"érzi",m:"Con trai",l:1},{h:"女儿",p:"nǚ'ér",m:"Con gái",l:1},
{h:"老师",p:"lǎoshī",m:"Giáo viên",l:1},{h:"学生",p:"xuéshēng",m:"Học sinh",l:1},
{h:"同学",p:"tóngxué",m:"Bạn cùng lớp",l:1},{h:"朋友",p:"péngyou",m:"Bạn bè",l:1},
{h:"医生",p:"yīshēng",m:"Bác sĩ",l:1},{h:"先生",p:"xiānsheng",m:"Ông, ngài",l:1},
{h:"小姐",p:"xiǎojiě",m:"Cô, tiểu thư",l:1},
{h:"吃",p:"chī",m:"Ăn",l:1},{h:"喝",p:"hē",m:"Uống",l:1},
{h:"看",p:"kàn",m:"Xem, nhìn",l:1},{h:"听",p:"tīng",m:"Nghe",l:1},
{h:"说",p:"shuō",m:"Nói",l:1},{h:"读",p:"dú",m:"Đọc",l:1},
{h:"写",p:"xiě",m:"Viết",l:1},{h:"学习",p:"xuéxí",m:"Học tập",l:1},
{h:"工作",p:"gōngzuò",m:"Làm việc",l:1},{h:"睡觉",p:"shuìjiào",m:"Ngủ",l:1},
{h:"买",p:"mǎi",m:"Mua",l:1},{h:"开",p:"kāi",m:"Mở",l:1},
{h:"坐",p:"zuò",m:"Ngồi",l:1},{h:"住",p:"zhù",m:"Ở, sống",l:1},
{h:"来",p:"lái",m:"Đến",l:1},{h:"去",p:"qù",m:"Đi",l:1},
{h:"回",p:"huí",m:"Về, quay lại",l:1},{h:"叫",p:"jiào",m:"Gọi, tên là",l:1},
{h:"想",p:"xiǎng",m:"Muốn, nghĩ",l:1},{h:"认识",p:"rènshi",m:"Quen biết",l:1},
{h:"会",p:"huì",m:"Biết, có thể",l:1},{h:"能",p:"néng",m:"Có thể",l:1},
{h:"喜欢",p:"xǐhuan",m:"Thích",l:1},{h:"爱",p:"ài",m:"Yêu",l:1},
{h:"做",p:"zuò",m:"Làm",l:1},{h:"打电话",p:"dǎ diànhuà",m:"Gọi điện thoại",l:1},
{h:"米饭",p:"mǐfàn",m:"Cơm",l:1},{h:"菜",p:"cài",m:"Rau, món ăn",l:1},
{h:"水果",p:"shuǐguǒ",m:"Trái cây",l:1},{h:"苹果",p:"píngguǒ",m:"Táo",l:1},
{h:"茶",p:"chá",m:"Trà",l:1},{h:"水",p:"shuǐ",m:"Nước",l:1},
{h:"杯子",p:"bēizi",m:"Cốc, ly",l:1},{h:"钱",p:"qián",m:"Tiền",l:1},
{h:"飞机",p:"fēijī",m:"Máy bay",l:1},{h:"出租车",p:"chūzūchē",m:"Taxi",l:1},
{h:"电脑",p:"diànnǎo",m:"Máy tính",l:1},{h:"电视",p:"diànshì",m:"Tivi",l:1},
{h:"电影",p:"diànyǐng",m:"Phim",l:1},{h:"天气",p:"tiānqì",m:"Thời tiết",l:1},
{h:"猫",p:"māo",m:"Mèo",l:1},{h:"狗",p:"gǒu",m:"Chó",l:1},
{h:"书",p:"shū",m:"Sách",l:1},{h:"汉语",p:"Hànyǔ",m:"Tiếng Trung",l:1},
{h:"字",p:"zì",m:"Chữ",l:1},{h:"名字",p:"míngzi",m:"Tên",l:1},
{h:"对不起",p:"duìbuqǐ",m:"Xin lỗi",l:1},{h:"没关系",p:"méi guānxi",m:"Không sao",l:1},
{h:"谢谢",p:"xièxie",m:"Cảm ơn",l:1},{h:"不客气",p:"bú kèqi",m:"Không có gì",l:1},
{h:"再见",p:"zàijiàn",m:"Tạm biệt",l:1},{h:"请",p:"qǐng",m:"Mời, xin",l:1},
{h:"你好",p:"nǐ hǎo",m:"Xin chào",l:1},{h:"在",p:"zài",m:"Ở, đang",l:1},
{h:"的",p:"de",m:"Của (trợ từ)",l:1},{h:"了",p:"le",m:"Rồi (trợ từ)",l:1},
{h:"吗",p:"ma",m:"Không? (trợ từ nghi vấn)",l:1},{h:"呢",p:"ne",m:"Còn...thì sao?",l:1},
{h:"都",p:"dōu",m:"Đều, tất cả",l:1},{h:"也",p:"yě",m:"Cũng",l:1},
{h:"很",p:"hěn",m:"Rất",l:1},{h:"太",p:"tài",m:"Quá",l:1},
{h:"和",p:"hé",m:"Và",l:1},{h:"在",p:"zài",m:"Đang (tiến hành)",l:1},
{h:"衣服",p:"yīfu",m:"Quần áo",l:1},{h:"桌子",p:"zhuōzi",m:"Bàn",l:1},
{h:"椅子",p:"yǐzi",m:"Ghế",l:1},{h:"下雨",p:"xià yǔ",m:"Mưa",l:1},
// HSK 2
{h:"因为",p:"yīnwèi",m:"Bởi vì",l:2},{h:"所以",p:"suǒyǐ",m:"Cho nên",l:2},
{h:"但是",p:"dànshì",m:"Nhưng mà",l:2},{h:"虽然",p:"suīrán",m:"Mặc dù",l:2},
{h:"如果",p:"rúguǒ",m:"Nếu",l:2},{h:"或者",p:"huòzhě",m:"Hoặc là",l:2},
{h:"还是",p:"háishi",m:"Hay là",l:2},{h:"除了",p:"chúle",m:"Ngoài ra",l:2},
{h:"从",p:"cóng",m:"Từ",l:2},{h:"向",p:"xiàng",m:"Hướng về",l:2},
{h:"离",p:"lí",m:"Cách (khoảng cách)",l:2},{h:"对",p:"duì",m:"Đúng, đối với",l:2},
{h:"比",p:"bǐ",m:"So với",l:2},{h:"跟",p:"gēn",m:"Với, theo",l:2},
{h:"就",p:"jiù",m:"Liền, thì",l:2},{h:"才",p:"cái",m:"Mới (thời gian)",l:2},
{h:"已经",p:"yǐjīng",m:"Đã rồi",l:2},{h:"正在",p:"zhèngzài",m:"Đang",l:2},
{h:"一直",p:"yìzhí",m:"Luôn luôn",l:2},{h:"又",p:"yòu",m:"Lại (lần nữa)",l:2},
{h:"再",p:"zài",m:"Lại, nữa",l:2},{h:"还",p:"hái",m:"Còn, vẫn",l:2},
{h:"最",p:"zuì",m:"Nhất",l:2},{h:"更",p:"gèng",m:"Hơn nữa",l:2},
{h:"非常",p:"fēicháng",m:"Rất, vô cùng",l:2},{h:"真",p:"zhēn",m:"Thật sự",l:2},
{h:"快",p:"kuài",m:"Nhanh",l:2},{h:"慢",p:"màn",m:"Chậm",l:2},
{h:"早",p:"zǎo",m:"Sớm",l:2},{h:"晚",p:"wǎn",m:"Muộn, tối",l:2},
{h:"长",p:"cháng",m:"Dài",l:2},{h:"新",p:"xīn",m:"Mới",l:2},
{h:"旧",p:"jiù",m:"Cũ",l:2},{h:"远",p:"yuǎn",m:"Xa",l:2},
{h:"近",p:"jìn",m:"Gần",l:2},{h:"贵",p:"guì",m:"Đắt",l:2},
{h:"便宜",p:"piányi",m:"Rẻ",l:2},{h:"错",p:"cuò",m:"Sai",l:2},
{h:"清楚",p:"qīngchu",m:"Rõ ràng",l:2},{h:"简单",p:"jiǎndān",m:"Đơn giản",l:2},
{h:"容易",p:"róngyì",m:"Dễ dàng",l:2},{h:"难",p:"nán",m:"Khó",l:2},
{h:"重要",p:"zhòngyào",m:"Quan trọng",l:2},{h:"特别",p:"tèbié",m:"Đặc biệt",l:2},
{h:"一样",p:"yíyàng",m:"Giống nhau",l:2},{h:"不同",p:"bùtóng",m:"Khác nhau",l:2},
{h:"健康",p:"jiànkāng",m:"Khỏe mạnh",l:2},{h:"生病",p:"shēngbìng",m:"Bị bệnh",l:2},
{h:"快乐",p:"kuàilè",m:"Vui vẻ, hạnh phúc",l:2},{h:"着急",p:"zháojí",m:"Lo lắng, vội",l:2},
{h:"担心",p:"dānxīn",m:"Lo lắng",l:2},{h:"满意",p:"mǎnyì",m:"Hài lòng",l:2},
{h:"相信",p:"xiāngxìn",m:"Tin tưởng",l:2},{h:"希望",p:"xīwàng",m:"Hy vọng",l:2},
{h:"觉得",p:"juéde",m:"Cảm thấy",l:2},{h:"知道",p:"zhīdào",m:"Biết",l:2},
{h:"了解",p:"liǎojiě",m:"Hiểu rõ",l:2},{h:"明白",p:"míngbai",m:"Hiểu",l:2},
{h:"记得",p:"jìde",m:"Nhớ",l:2},{h:"忘记",p:"wàngjì",m:"Quên",l:2},
{h:"告诉",p:"gàosu",m:"Nói cho biết",l:2},{h:"回答",p:"huídá",m:"Trả lời",l:2},
{h:"问题",p:"wèntí",m:"Câu hỏi, vấn đề",l:2},{h:"答案",p:"dá'àn",m:"Đáp án",l:2},
{h:"考试",p:"kǎoshì",m:"Thi",l:2},{h:"成绩",p:"chéngjì",m:"Thành tích",l:2},
{h:"练习",p:"liànxí",m:"Luyện tập",l:2},{h:"复习",p:"fùxí",m:"Ôn tập",l:2},
{h:"准备",p:"zhǔnbèi",m:"Chuẩn bị",l:2},{h:"完成",p:"wánchéng",m:"Hoàn thành",l:2},
{h:"开始",p:"kāishǐ",m:"Bắt đầu",l:2},{h:"结束",p:"jiéshù",m:"Kết thúc",l:2},
{h:"帮助",p:"bāngzhù",m:"Giúp đỡ",l:2},{h:"解决",p:"jiějué",m:"Giải quyết",l:2},
{h:"需要",p:"xūyào",m:"Cần",l:2},{h:"必须",p:"bìxū",m:"Phải, bắt buộc",l:2},
{h:"可以",p:"kěyǐ",m:"Có thể, được phép",l:2},{h:"应该",p:"yīnggāi",m:"Nên",l:2},
{h:"可能",p:"kěnéng",m:"Có thể (khả năng)",l:2},{h:"愿意",p:"yuànyì",m:"Sẵn lòng",l:2},
{h:"同意",p:"tóngyì",m:"Đồng ý",l:2},{h:"注意",p:"zhùyì",m:"Chú ý",l:2},
{h:"参加",p:"cānjiā",m:"Tham gia",l:2},{h:"经常",p:"jīngcháng",m:"Thường xuyên",l:2},
{h:"总是",p:"zǒngshì",m:"Luôn luôn",l:2},{h:"有时候",p:"yǒu shíhou",m:"Đôi khi",l:2},
{h:"刚才",p:"gāngcái",m:"Vừa mới",l:2},{h:"马上",p:"mǎshàng",m:"Ngay lập tức",l:2},
{h:"终于",p:"zhōngyú",m:"Cuối cùng",l:2},{h:"忽然",p:"hūrán",m:"Đột nhiên",l:2},
{h:"渐渐",p:"jiànjiàn",m:"Dần dần",l:2},{h:"越来越",p:"yuèláiyuè",m:"Ngày càng",l:2},
{h:"一边",p:"yìbiān",m:"Vừa...vừa",l:2},{h:"先",p:"xiān",m:"Trước",l:2},
{h:"然后",p:"ránhòu",m:"Sau đó",l:2},{h:"最后",p:"zuìhòu",m:"Cuối cùng",l:2},
{h:"丈夫",p:"zhàngfu",m:"Chồng",l:2},{h:"妻子",p:"qīzi",m:"Vợ",l:2},
{h:"哥哥",p:"gēge",m:"Anh trai",l:2},{h:"姐姐",p:"jiějie",m:"Chị gái",l:2},
{h:"弟弟",p:"dìdi",m:"Em trai",l:2},{h:"妹妹",p:"mèimei",m:"Em gái",l:2},
{h:"爷爷",p:"yéye",m:"Ông nội",l:2},{h:"奶奶",p:"nǎinai",m:"Bà nội",l:2},
{h:"孩子",p:"háizi",m:"Đứa trẻ",l:2},{h:"男人",p:"nánrén",m:"Đàn ông",l:2},
{h:"女人",p:"nǚrén",m:"Phụ nữ",l:2},{h:"邻居",p:"línjū",m:"Hàng xóm",l:2},
{h:"客人",p:"kèrén",m:"Khách",l:2},{h:"司机",p:"sījī",m:"Tài xế",l:2},
{h:"经理",p:"jīnglǐ",m:"Giám đốc",l:2},{h:"服务员",p:"fúwùyuán",m:"Nhân viên phục vụ",l:2},
{h:"身体",p:"shēntǐ",m:"Cơ thể",l:2},{h:"眼睛",p:"yǎnjing",m:"Mắt",l:2},
{h:"耳朵",p:"ěrduo",m:"Tai",l:2},{h:"鼻子",p:"bízi",m:"Mũi",l:2},
{h:"嘴",p:"zuǐ",m:"Miệng",l:2},{h:"头",p:"tóu",m:"Đầu",l:2},
{h:"手",p:"shǒu",m:"Tay",l:2},{h:"脚",p:"jiǎo",m:"Chân",l:2},
{h:"脸",p:"liǎn",m:"Mặt",l:2},
{h:"教室",p:"jiàoshì",m:"Phòng học",l:2},{h:"办公室",p:"bàngōngshì",m:"Văn phòng",l:2},
{h:"超市",p:"chāoshì",m:"Siêu thị",l:2},{h:"公园",p:"gōngyuán",m:"Công viên",l:2},
{h:"银行",p:"yínháng",m:"Ngân hàng",l:2},{h:"机场",p:"jīchǎng",m:"Sân bay",l:2},
{h:"地方",p:"dìfang",m:"Nơi, chỗ",l:2},{h:"城市",p:"chéngshì",m:"Thành phố",l:2},
{h:"公司",p:"gōngsī",m:"Công ty",l:2},
{h:"唱歌",p:"chànggē",m:"Hát",l:2},{h:"跳舞",p:"tiàowǔ",m:"Nhảy múa",l:2},
{h:"游泳",p:"yóuyǒng",m:"Bơi",l:2},{h:"跑步",p:"pǎobù",m:"Chạy bộ",l:2},
{h:"旅游",p:"lǚyóu",m:"Du lịch",l:2},{h:"运动",p:"yùndòng",m:"Thể thao",l:2},
{h:"生日",p:"shēngrì",m:"Sinh nhật",l:2},{h:"节日",p:"jiérì",m:"Lễ, tết",l:2},
{h:"春节",p:"Chūnjié",m:"Tết Nguyên Đán",l:2},
{h:"手机",p:"shǒujī",m:"Điện thoại di động",l:2},{h:"地铁",p:"dìtiě",m:"Tàu điện ngầm",l:2},
{h:"公共汽车",p:"gōnggòng qìchē",m:"Xe buýt",l:2},{h:"自行车",p:"zìxíngchē",m:"Xe đạp",l:2},
{h:"护照",p:"hùzhào",m:"Hộ chiếu",l:2},{h:"地图",p:"dìtú",m:"Bản đồ",l:2},
{h:"照片",p:"zhàopiàn",m:"Ảnh chụp",l:2},{h:"作业",p:"zuòyè",m:"Bài tập",l:2},
{h:"报纸",p:"bàozhǐ",m:"Báo",l:2},{h:"词典",p:"cídiǎn",m:"Từ điển",l:2},
{h:"句子",p:"jùzi",m:"Câu (ngữ pháp)",l:2},{h:"故事",p:"gùshi",m:"Câu chuyện",l:2},
{h:"音乐",p:"yīnyuè",m:"Âm nhạc",l:2},{h:"颜色",p:"yánsè",m:"Màu sắc",l:2},
{h:"红",p:"hóng",m:"Đỏ",l:2},{h:"白",p:"bái",m:"Trắng",l:2},
{h:"黑",p:"hēi",m:"Đen",l:2},{h:"蓝",p:"lán",m:"Xanh dương",l:2},
{h:"绿",p:"lǜ",m:"Xanh lá",l:2},{h:"黄",p:"huáng",m:"Vàng",l:2}
];
